"""Configuration, chemins et dependances optionnelles."""

from .core import (
    APP_ROOT,
    BALROG_1G1R_ICON,
    BALROG_ASSETS_DIR,
    BALROG_WINDOW_ICON,
    DEFAULT_CONFIG_URLS,
    DEFAULT_PARALLEL_DOWNLOADS,
    PREFERENCES_FILE,
    RESOLUTION_CACHE_FILE,
    ROM_EXTENSIONS,
    SCAN_CACHE_FILENAME,
    build_diagnostic_report,
    clear_resolution_cache,
    export_diagnostic_report,
    format_bytes,
    import_optional_package,
    install_python_packages,
    load_env_file,
    load_preferences,
    print_diagnostic_report,
    save_preferences,
)

__all__ = [
    "APP_ROOT",
    "BALROG_1G1R_ICON",
    "BALROG_ASSETS_DIR",
    "BALROG_WINDOW_ICON",
    "DEFAULT_CONFIG_URLS",
    "DEFAULT_PARALLEL_DOWNLOADS",
    "PREFERENCES_FILE",
    "RESOLUTION_CACHE_FILE",
    "ROM_EXTENSIONS",
    "SCAN_CACHE_FILENAME",
    "build_diagnostic_report",
    "clear_resolution_cache",
    "export_diagnostic_report",
    "format_bytes",
    "import_optional_package",
    "install_python_packages",
    "load_env_file",
    "load_preferences",
    "print_diagnostic_report",
    "save_preferences",
]
